export const START_STICKERS = [
  'CAACAgQAAxkBAAMIZ79JvvER4Iyto73wQRL_3clb03kAAiAPAAIPUolQdne1U37SlWY2BA',
  'CAACAgIAAxkBAAEyU8BnxsVTvw8b2G5wXf_XH4lXzzNNAQACViYAAuQ4SUj_2sn-FralTjYE',
  'CAACAgIAAxkBAAEyU8pnxsX6PjsTUUalXtcMvpsQNrFckAACUBcAApeY4Usz0JhWpYQEOjYE',
  'CAACAgIAAxkBAAEyU8xnxsYkerbxsDd03RKaWc8zI422LgACPBMAAoElyUsiXeSDccqJwzYE',
  'CAACAgIAAxkBAAEyU9BnxsaFlC2y_Fhqx_418sulayIBfAAC6V8AAiubOUg6U6Xc9fsn2jYE',
  'CAACAgIAAxkBAAEyU9Znxsb2vOjfTq3ETv3odI244xEGLgACcU4AAq3Z2EubO3uToL41sTYE',
  'CAACAgIAAxkBAAEyU9hnxscAAYdtezP4BRXK_OAAAdZGl6YvAALoRgACuTjZS8CPFN7K0J1oNgQ',
  'CAACAgIAAxkBAAEyU-xnxspAbdS__gbFXq5d2PNSOHEBswACJGsAAqxDQUj_sV94Em5h5TYE',
  "CAACAgIAAxkBAAEyZDpnyPVZ8yyypSjzTJP_YFe2fnavXQACKEIAAvfZcEj5t2U7VpysczYE",
  "CAACAgIAAxkBAAEyZEJnyPXmCAyzAmkkIsllCU4jrubDCAACAQQAAnwFBxsvxAgGEP6cpjYE",
  "CAACAgIAAxkBAAEyZEtnyPZSaY-yHamdzbr6GeSa0NHXdAAC_BMAAudZeEhulydYNbA9JDYE",

];

export const CONFIRMATION_STICKERS = [
  'CAACAgQAAxkBAAEyUu1nxqm5Pb929A6hflPdr9juOTYVCQACXgoAAlxe8FIPl_gc6gMD3zYE',
  'CAACAgIAAxkBAAEyU7JnxsR2e-YHasLnEo2aZtEJvPBrCQACVBQAAnaCKUgX-pOEUFFw4TYE',
  'CAACAgIAAxkBAAEyU7pnxsUioxXLrAcLlj0-HhmtX8DIbAACsB8AAsna0EqKnaNDLPuKoDYE',
  'CAACAgQAAxkBAAEyU8JnxsV5mv9ws7WcWusiEBOLMLjdFwACCxUAAiFscFA5yVu4im_dpDYE',
  'CAACAgQAAxkBAAEyU8RnxsWqIwcWtLH7Xg5Ju9n8vMFLNgACdA0AAioguVAkVAABtP0dXOI2BA',
  'CAACAgIAAxkBAAEyU9RnxsavBGwSnAppGn9Szs53GgZZUwACwj4AAjiOcEteZMi1_Q4LpjYE',
  'CAACAgIAAxkBAAEyU9pnxsdNXw3_duKJ8Y6q1rBcaRKKQAACHCQAApd_-UtQdpyIPq2w4DYE',
  'CAACAgIAAxkBAAEyU9xnxsfdFTgAAWo0xjso75Ky-zj-cb4AAjZnAAKDFWhIupEMOQrO0Pw2BA',
  "CAACAgIAAxkBAAEyZBxnyPPrjMK8H6JYf48-3o1Nv1RT1QACuUQAAuckuEot6gIKoOR92TYE",
  "CAACAgIAAxkBAAEyZDBnyPUJah2-f3VjtwMpNWrV8p89MQACc1UAAmJwCEjbAoLEOzDa8jYE",
  "CAACAgIAAxkBAAEyZERnyPX9CYiMb_-7K7cZupEORgWnsgACBAQAAnwFBxvMOWelU5qcnzYE",

];


export const DELETE_STICKERS = [
  "CAACAgIAAxkBAAEyZAhnyPNS64MhpqxkzBFbleqNEDxaTAACPhUAAuE7yEshrvTovPQkDzYE",
  "CAACAgIAAxkBAAEyZBFnyPNzf4Ibv24CZD4O4dvwv8iYvAACtRIAAgvQ2EuymyxgBSvSAjYE",
  "CAACAgIAAxkBAAEyZBZnyPOiVV1tYuF_MROFZw1_oc7RpAACaRUAAuLiyUsN3Y_gFzxdajYE",
  "CAACAgIAAxkBAAEyZBhnyPPH0ybIpzfEDFF58qPOrK008AACIWEAApTtyEv5laj_sN8y-zYE",
  "CAACAgIAAxkBAAEyZCJnyPRmYE77oO_eWt0_Wzlka0w0OwACfkwAAunTcEur9M8AAWFt8jo2BA",
  "CAACAgIAAxkBAAEyZCZnyPStD8EQVOhzNFYS0sw8UlSV4gAC-2IAAmzeIUj6FT-Nr3iytjYE",
  "CAACAgIAAxkBAAEyZDJnyPUjmXsfNw8irXot_yt6ZMnZbQAC0TwAArbfaEi9HxEXCcrMcTYE",
  "CAACAgIAAxkBAAEyZDRnyPUy8HdR1mUSfsSK135gMqwvdgACSDwAAqQ2aEjyh0L4L5r9uTYE",
  "CAACAgIAAxkBAAEyZDxnyPVyXXFUuMz4PEcEKXfmn5IvpAACCAQAAnwFBxt7kJy3Xb-xDTYE",
  "CAACAgIAAxkBAAEyZFFnyPaU2yLN_5HPxygIRy4PJtqO7AACLBIAAjp2MEi51s0WhdeJzDYE",
  "CAACAgIAAxkBAAEyZFVnyPbYM0bSU3XAdhqRf55jDOzOaAACkhoAAvLJSUhMKNQ2rSABxzYE",

];

export const GOODBYE_STICKERS = [
  "CAACAgQAAxkBAAEyY-pnyO_d6t5U6kXn3JvhwsSabQHRxAACkw8AAnkyWFMQH20wKdJOujYE",
  "CAACAgQAAxkBAAEyY-hnyO_NCkn0CJuHr31DZh6G73UzJAACdBcAApjaWFC4pPqP6N0GkTYE",
  "CAACAgQAAxkBAAEyY-ZnyO_AljI97EL-B6_KXO4LH-_sowAC2RUAAvjjgVLRK-Gy-VUvkDYE",
  "CAACAgQAAxkBAAEyY-JnyO-3L4biTcs2_O5ghDuUJjkIWQACWgoAAispwFDPw6uJgC-lGzYE",
  "CAACAgQAAxkBAAEyY_5nyPLPLRo9JlMQWI4DCwZf_eO8zwACAw4AAk8NWFGD1gpp9GMBMDYE",
  "CAACAgQAAxkBAAEyZAJnyPL0hnzHjgGDAT8MFxBoijpstQACZA8AAu4zAVIGN56R0-1HxjYE",
  "CAACAgIAAxkBAAEyZFNnyPbIoibHX-3wsQGhZYr9i6BM-QACpxIAAtxBUEiiUyP5TQABlb02BA",

];

export const ERROR_STICKERS = [
  "CAACAgIAAxkBAAEyY-BnyO-MJsRTTtBVFLqrKUfmBGDB9wACJhIAAgO7yUtW2VDH_raR8zYE",
  "CAACAgQAAxkBAAEyY_ZnyPJ0URq03WStZFpOFciA3_nYMQACexMAAsgqYFAriCzdxEH5rjYE",
  "CAACAgQAAxkBAAEyY_hnyPKKxNlojvI1BD6O4JarBMBiDwAC9AwAAkGzQFJoIsgjG9PW4DYE",
  "CAACAgQAAxkBAAEyY_pnyPKY3vAZjZWFXRtElrbrxXj4LgACkg0AAmJr8VLbGNJOy7UFcTYE",
  "CAACAgQAAxkBAAEyY_xnyPK53aPy8baHJ8dJNQ4QfDNnFAACzxgAAkEniVCunupOChAxFTYE",
  "CAACAgQAAxkBAAEyZAABZ8jy2mjZE8WDspZA9I2SmnN_qTkAAt0XAALZsWFQcGprtVRar4k2BA",
  "CAACAgQAAxkBAAEyZARnyPMTHwO1IwfCQbRQGaBEub87HAACjA8AAnOPyVMWtl8bdIl9BTYE",
  "CAACAgIAAxkBAAEyZAZnyPMrvUD-eHJ-IywVHLJ95Avz-QACrBQAAgFUyUsW0DZ-wGJ9HzYE",
  "CAACAgIAAxkBAAEyZCtnyPTBAUhIiTexpHTdwsfZ9ZK7ygAClg4AAoFcYEguu61CNKUlfDYE",
  "CAACAgIAAxkBAAEyZE1nyPZoXAnTF2WECV3J3UUZ_HWBPAACwhEAAgdjCEjjlu6QnkifbjYE",

];

export const STICKERS = {
  CONFIRMATION: CONFIRMATION_STICKERS,
  START: START_STICKERS,
  DELETE: DELETE_STICKERS,
  GOODBYE: GOODBYE_STICKERS,
  ERROR: ERROR_STICKERS,
};

